import "Graph.idl";
namespace Irregular_Sliding_Puzzle
{
    [default_interface]
    runtimeclass DesignGame : Microsoft.UI.Xaml.Controls.Page
    {
        DesignGame();
        void Init(UInt8 height, UInt8 width, IVector< IVector<Boolean> > board, Graph g, Boolean mode);
    }
}
