namespace Irregular_Sliding_Puzzle
{
    delegate void VV(Object v);
    delegate Boolean VB(Object v);
	delegate void EV(Object e, Object u, Object v);
	delegate Boolean EB(Object e, Object u, Object v);
    delegate void NV(Object e, Object v);
    delegate Boolean NB(Object e, Object v);

    [default_interface]
    runtimeclass Graph
    {
        Graph();
        void AddVertex(Object v);
		void EraseVertex(Object v);
        void AddEdge(Object e, Object u, Object v);
		void EraseEdge(Object e, Object u, Object v);
		void ForEachVertex(VV func);
		Boolean ForEachVertex2(VB func);
		void ForEachEdge(EV func);
		Boolean ForEachEdge2(EB func);
        void ForEachNeighbor(Object v, NV func);
        Boolean ForEachNeighbor2(Object v, NB func);
        UInt32 VertexCount{ get; };
        UInt32 EdgeCount{ get; };
		UInt32 Degree(Object v);
        void ClearEdges();
        void Clear();
    }
}
